framework:
    html_sanitizer:
        sanitizers:
            default:
                allow_safe_elements: true
                allowed_css_properties:
                    - color
                    - background-color
                    - font
                    - font-family
                    - font-size
                    - font-style
                    - font-weight
                    - text-align
                    - text-decoration
                    - text-transform
                    - line-height
                    - letter-spacing
                    - word-spacing
                    - width
                    - height
                    - margin
                    - margin-top
                    - margin-bottom
                    - margin-left
                    - margin-right
                    - padding
                    - padding-top
                    - padding-bottom
                    - padding-left
                    - padding-right
