services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: app
        restart: always
        depends_on:
            - mysql
        working_dir: /var/www/
        volumes:
            - ../:/var/www

    node:
        image: node:18-alpine
        container_name: node
        working_dir: /var/www
        volumes:
            - ../:/var/www
        command: sh -c "npm install && npm run build && npm run watch"
        depends_on:
            - app

    mjml:
        build:
            context: ../
            dockerfile: docker/mjml-service.Dockerfile
        container_name: mjml-service
        restart: always
        ports:
            - "3001:3000"
        volumes:
            - ../mjml-service:/app
            - /app/node_modules

    openai:
        build:
            context: ../
            dockerfile: docker/openai-service.Dockerfile
        container_name: openai-service
        restart: always
        ports:
            - "4001:4000"
        volumes:
            - ../openai-service:/app
            - /app/node_modules
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}

    nginx:
        image: nginx:1.27.5-alpine
        container_name: nginx
        restart: always
        depends_on:
            - mysql
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d

    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: app
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - "3308:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "9000:80"

    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:management-alpine
        restart: unless-stopped
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        ports:
            - "15674:15672"
            - "5674:5672"
        environment:
            - RABBITMQ_NODENAME=node@rabbitmq

volumes:
    mysql_data:
    rabbitmq:
